import { ICanvasDocument } from "@/interfaces/canvas-editor.interface";

export const INITIAL_WEDDING_CANVAS: ICanvasDocument = {
  id: "card-canvas-default",
  title: "Thiệp Mời Hoàng Kim Minh Quân & Thanh Trúc",
  width: 390,
  height: 2180, // Chiều cao sang trọng, thoáng đạt
  backgroundColor: "#FAF7F2",
  openingEffect: "envelope-3d",
  ambientParticle: "sakura",
  layers: [
    // ==================== PHẦN 1: BÌA THIỆP & TÊN CHỦ NHÂN ====================
    // 1. Khung Viền Vàng Hoàng Kim Toàn Bộ Thiệp
    {
      id: "layer-border-outer",
      type: "shape",
      name: "Khung Viền Chính",
      shapeType: "rect",
      x: 14,
      y: 14,
      width: 362,
      height: 2152,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 1,
      isLocked: true,
      isHidden: false,
      fill: "transparent",
      stroke: "#D4AF37",
      strokeWidth: 1.5,
      borderRadius: 24,
    },
    // 2. Viền Hoa Văn Mảnh Trong
    {
      id: "layer-border-inner",
      type: "shape",
      name: "Viền Mảnh Trong",
      shapeType: "rect",
      x: 20,
      y: 20,
      width: 350,
      height: 2140,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 2,
      isLocked: true,
      isHidden: false,
      fill: "transparent",
      stroke: "rgba(212, 175, 55, 0.35)",
      strokeWidth: 1,
      borderRadius: 18,
    },
    // 3. Nơ Lụa Đỏ / Họa Tiết Đỉnh Thiệp
    {
      id: "layer-sticker-top",
      type: "sticker",
      name: "Họa Tiết Nơ Đỉnh Thiệp",
      stickerType: "emoji",
      content: "🎀",
      x: 0,
      y: 36,
      width: 390,
      fontSize: 38,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 3,
      isLocked: false,
      isHidden: false,
    },
    // 4. "Thư mời tham dự"
    {
      id: "layer-txt-subtitle",
      type: "text",
      name: "Thư Mời Tham Dự",
      text: "Thư mời tham dự",
      fontSize: 16,
      fontFamily: "'Playfair Display', serif",
      fontStyle: "italic",
      fontWeight: "normal",
      fill: "#9E6B38",
      textAlign: "center",
      x: 0,
      y: 82,
      width: 390,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 4,
      isLocked: false,
      isHidden: false,
    },
    // 5. Tiêu Đề Sự Kiện: "LỄ THÀNH HÔN"
    {
      id: "layer-txt-ceremony",
      type: "text",
      name: "Tiêu Đề Lễ",
      text: "LỄ THÀNH HÔN",
      fontSize: 22,
      fontFamily: "'Playfair Display', serif",
      fontWeight: "bold",
      fill: "#851C24",
      textAlign: "center",
      letterSpacing: 4,
      x: 0,
      y: 112,
      width: 390,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 5,
      isLocked: false,
      isHidden: false,
    },
    // 6. Tên Chú Rể & Cô Dâu
    {
      id: "layer-txt-couple",
      type: "text",
      name: "Tên Chú Rể & Cô Dâu",
      text: "MINH QUÂN & THANH TRÚC",
      fontSize: 19,
      fontFamily: "'Playfair Display', serif",
      fontWeight: "bold",
      fill: "#851C24",
      textAlign: "center",
      letterSpacing: 2,
      x: 0,
      y: 148,
      width: 390,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 6,
      isLocked: false,
      isHidden: false,
    },
    // 7. Ảnh Bìa Vòm Cổng Hoàng Gia
    {
      id: "layer-img-main",
      type: "image",
      name: "Ảnh Cưới Bìa Chính",
      src: "/images/anh-mau-1.jpg",
      x: 45,
      y: 195,
      width: 300,
      height: 380,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 7,
      isLocked: false,
      isHidden: false,
      borderRadius: 130, // Vòm cong nghệ thuật như mẫu
      opacity: 1,
    },
    // 8. Dải Phân Cách Mảnh Vàng 1
    {
      id: "layer-div-1",
      type: "shape",
      name: "Phân Cách Phần 1",
      shapeType: "divider",
      x: 95,
      y: 595,
      width: 200,
      height: 1.5,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 8,
      isLocked: false,
      isHidden: false,
      fill: "#D4AF37",
      stroke: "#D4AF37",
      strokeWidth: 1,
    },

    // ==================== PHẦN 2: THỜI GIAN & LỊCH SAVE THE DATE ====================
    // 9. Khung Thông Tin Ngày & Giờ (Event Info Widget)
    {
      id: "layer-event-info",
      type: "event-info",
      name: "Khung Thời Gian",
      dateLabel: "NGÀY",
      dateValue: "Chủ Nhật\n20.11.2026",
      timeLabel: "GIỜ",
      timeValue: "Đón khách\n18:00",
      primaryColor: "#851C24",
      accentColor: "#E2D3BE",
      x: 45,
      y: 615,
      width: 300,
      height: 60,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 9,
      isLocked: false,
      isHidden: false,
    },
    // 10. Thẻ Lịch Save The Date Nghệ Thuật (Calendar Widget)
    {
      id: "layer-cal-widget",
      type: "calendar",
      name: "Lịch Save The Date",
      monthTitle: "Tháng 11 / 2026",
      year: 2026,
      month: 11,
      startDayOfWeek: 6,
      daysCount: 30,
      selectedDay: 20,
      primaryColor: "#851C24",
      accentColor: "#EBDBC8",
      backgroundColor: "#FFFFFF",
      x: 45,
      y: 700,
      width: 300,
      height: 245,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 10,
      isLocked: false,
      isHidden: false,
    },

    // ==================== PHẦN 3: ĐỊA ĐIỂM TỔ CHỨC ====================
    // 11. Label Địa Điểm
    {
      id: "layer-txt-loc-label",
      type: "text",
      name: "Label Địa Điểm",
      text: "ĐỊA ĐIỂM",
      fontSize: 11,
      fontFamily: "Inter, sans-serif",
      fontWeight: "bold",
      fill: "#9E6B38",
      textAlign: "center",
      letterSpacing: 4,
      x: 0,
      y: 975,
      width: 390,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 11,
      isLocked: false,
      isHidden: false,
    },
    // 12. Icon Pin Địa Điểm
    {
      id: "layer-icon-loc",
      type: "sticker",
      name: "Icon Pin Vị Trí",
      stickerType: "emoji",
      content: "📍",
      x: 0,
      y: 998,
      width: 390,
      fontSize: 22,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 12,
      isLocked: false,
      isHidden: false,
    },
    // 13. Chi Tiết Địa Điểm
    {
      id: "layer-txt-loc-info",
      type: "text",
      name: "Tên & Địa Chỉ Nhà Hàng",
      text: "Trung Tâm Hội Nghị Park Hyatt Sài Gòn\nSố 2 Công Trường Lam Sơn, Bến Nghé, Quận 1, TP.HCM",
      fontSize: 13,
      fontFamily: "Inter, sans-serif",
      fontWeight: "bold",
      fill: "#851C24",
      textAlign: "center",
      lineHeight: 1.5,
      x: 35,
      y: 1030,
      width: 320,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 13,
      isLocked: false,
      isHidden: false,
    },
    // 14. Phân Cách Phần 3 & 4
    {
      id: "layer-div-2",
      type: "shape",
      name: "Phân Cách Phần 2",
      shapeType: "divider",
      x: 95,
      y: 1105,
      width: 200,
      height: 1.5,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 14,
      isLocked: false,
      isHidden: false,
      fill: "#D4AF37",
      stroke: "#D4AF37",
      strokeWidth: 1,
    },

    // ==================== PHẦN 4: LỊCH TRÌNH SỰ KIỆN ====================
    // 15. Lịch Trình Sự Kiện Sang Trọng (Timeline Widget)
    {
      id: "layer-timeline-widget",
      type: "timeline",
      name: "Lịch Trình Sự Kiện",
      title: "LỊCH TRÌNH SỰ KIỆN",
      primaryColor: "#851C24",
      accentColor: "#D4AF37",
      textColor: "#3B2F23",
      items: [
        { time: "17:30", title: "Đón Tiếp Khách Mời & Check-in", subTitle: "Chụp ảnh lưu niệm tại sảnh hoa" },
        { time: "18:30", title: "Lễ Thành Hôn Chính Thức", subTitle: "Nghi thức trao nhẫn & cắt bánh mừng" },
        { time: "19:00", title: "Khai Tiệc Mừng Hạnh Phúc", subTitle: "Thưởng thức ẩm thực & chúc mừng" },
        { time: "20:30", title: "Giao Lưu & Chụp Hình Lưu Niệm", subTitle: "Mini game & chia sẻ cảm xúc" },
        { time: "21:30", title: "Tạm Biệt & Lời Cảm Ơn Chân Thành", subTitle: "Trao quà cảm ơn khách mời" },
      ],
      x: 25,
      y: 1135,
      width: 340,
      height: 220,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 15,
      isLocked: false,
      isHidden: false,
    },

    // ==================== PHẦN 5: ĐẾM NGƯỢC THỜI GIAN ====================
    // 16. Hộp Đếm Ngược Thời Gian (Countdown Widget)
    {
      id: "layer-countdown-widget",
      type: "countdown",
      name: "Khung Đếm Ngược",
      title: "Đếm ngược đến giờ sự kiện",
      days: 13,
      hours: 15,
      minutes: 48,
      primaryColor: "#851C24",
      backgroundColor: "#FFFFFF",
      x: 45,
      y: 1385,
      width: 300,
      height: 105,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 16,
      isLocked: false,
      isHidden: false,
    },
    // 17. Phân Cách Phần 5 & 6
    {
      id: "layer-div-3",
      type: "shape",
      name: "Phân Cách Phần 3",
      shapeType: "divider",
      x: 95,
      y: 1515,
      width: 200,
      height: 1.5,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 17,
      isLocked: false,
      isHidden: false,
      fill: "#D4AF37",
      stroke: "#D4AF37",
      strokeWidth: 1,
    },

    // ==================== PHẦN 6: ALBUM ẢNH CƯỚI ====================
    // 18. Tiêu Đề Album Ảnh
    {
      id: "layer-txt-gallery-title",
      type: "text",
      name: "Tiêu Đề Album",
      text: "MỘT VÀI HÌNH ẢNH",
      fontSize: 16,
      fontFamily: "'Playfair Display', serif",
      fontWeight: "bold",
      fill: "#851C24",
      textAlign: "center",
      letterSpacing: 2,
      x: 0,
      y: 1540,
      width: 390,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 18,
      isLocked: false,
      isHidden: false,
    },
    // 19. Ảnh Album 1 (Trao tráp rước dâu)
    {
      id: "layer-img-gal-1",
      type: "image",
      name: "Ảnh Album 1",
      src: "/images/anh-mau-2.jpg",
      x: 38,
      y: 1580,
      width: 152,
      height: 195,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 19,
      isLocked: false,
      isHidden: false,
      borderRadius: 16,
      opacity: 1,
    },
    // 20. Ảnh Album 2 (Bạn bè chúc phúc)
    {
      id: "layer-img-gal-2",
      type: "image",
      name: "Ảnh Album 2",
      src: "/images/anh-mau-3.jpg",
      x: 200,
      y: 1580,
      width: 152,
      height: 195,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 20,
      isLocked: false,
      isHidden: false,
      borderRadius: 16,
      opacity: 1,
    },
    // 21. Ảnh Album 3 (Trao duyên hạnh phúc)
    {
      id: "layer-img-gal-3",
      type: "image",
      name: "Ảnh Album 3",
      src: "/images/anh-mau-4.jpg",
      x: 38,
      y: 1790,
      width: 152,
      height: 195,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 21,
      isLocked: false,
      isHidden: false,
      borderRadius: 16,
      opacity: 1,
    },
    // 22. Ảnh Album 4 (Chúc trà phụ mẫu)
    {
      id: "layer-img-gal-4",
      type: "image",
      name: "Ảnh Album 4",
      src: "/images/anh-mau-5.jpg",
      x: 200,
      y: 1790,
      width: 152,
      height: 195,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 22,
      isLocked: false,
      isHidden: false,
      borderRadius: 16,
      opacity: 1,
    },

    // ==================== PHẦN 7: LỜI CẢM ƠN & KẾT THIỆP ====================
    // 23. Lời Cảm Ơn Cuối Thiệp
    {
      id: "layer-txt-thanks",
      type: "text",
      name: "Lời Cảm Ơn",
      text: "Sự hiện diện của quý khách là niềm vinh hạnh lớn của gia đình chúng tôi!\n— Trân trọng cảm ơn —",
      fontSize: 12.5,
      fontFamily: "Inter, sans-serif",
      fontStyle: "italic",
      fontWeight: "normal",
      fill: "#6D5E4D",
      textAlign: "center",
      lineHeight: 1.5,
      x: 0,
      y: 2020,
      width: 390,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 23,
      isLocked: false,
      isHidden: false,
    },
    // 24. Họa Tiết Kết Thiệp
    {
      id: "layer-sticker-end",
      type: "sticker",
      name: "Họa Tiết Kết Thiệp",
      stickerType: "emoji",
      content: "⚜️ ✨ ⚜️",
      x: 0,
      y: 2085,
      width: 390,
      fontSize: 20,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 24,
      isLocked: false,
      isHidden: false,
    },
  ],
};
