import { ICanvasDocument } from "@/interfaces/canvas-editor.interface";

export const INITIAL_WEDDING_CANVAS: ICanvasDocument = {
  id: "card-canvas-default",
  title: "Thiệp Cưới Hoàng Kim Minh Quân & Thanh Trúc",
  width: 390,
  height: 1650, // Canvas cuộn dài đầy đủ các phần của thiệp cưới Mobile
  backgroundColor: "#FCFAF6",
  layers: [
    // ==================== PHẦN 1: BÌA THIỆP & TÊN CÔ DÂU CHÚ RỂ ====================
    // 1. Khung Viền Vàng Hoàng Kim Toàn Bộ Thiệp
    {
      id: "layer-border-outer",
      type: "shape",
      name: "Khung Viền Chính",
      shapeType: "rect",
      x: 16,
      y: 16,
      width: 358,
      height: 1618,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 1,
      isLocked: true,
      isHidden: false,
      fill: "transparent",
      stroke: "#C59B4B",
      strokeWidth: 1.5,
      borderRadius: 20,
    },
    // 2. Viền Hoa Văn Mảnh Trong
    {
      id: "layer-border-inner",
      type: "shape",
      name: "Viền Hoa Văn Trong",
      shapeType: "rect",
      x: 22,
      y: 22,
      width: 346,
      height: 1606,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 2,
      isLocked: true,
      isHidden: false,
      fill: "transparent",
      stroke: "rgba(197, 155, 75, 0.3)",
      strokeWidth: 1,
      borderRadius: 16,
    },
    // 3. Biểu Tượng Vương Miện
    {
      id: "layer-crest-top",
      type: "sticker",
      name: "Họa Tiết Đỉnh Thiệp",
      stickerType: "emoji",
      content: "⚜️",
      x: 0,
      y: 38,
      width: 390,
      fontSize: 26,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 3,
      isLocked: false,
      isHidden: false,
    },
    // 4. "SAVE THE DATE"
    {
      id: "layer-txt-save-date",
      type: "text",
      name: "Save The Date",
      text: "SAVE THE DATE",
      fontSize: 12,
      fontFamily: "Inter, sans-serif",
      fontWeight: "bold",
      fill: "#B78628",
      textAlign: "center",
      letterSpacing: 4,
      x: 0,
      y: 72,
      width: 390,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 4,
      isLocked: false,
      isHidden: false,
    },
    // 5. "LỄ THÀNH HÔN"
    {
      id: "layer-txt-ceremony",
      type: "text",
      name: "Lễ Thành Hôn",
      text: "LỄ THÀNH HÔN",
      fontSize: 15,
      fontFamily: "'Playfair Display', serif",
      fontWeight: "bold",
      fill: "#3B2F23",
      textAlign: "center",
      letterSpacing: 3,
      x: 0,
      y: 96,
      width: 390,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 5,
      isLocked: false,
      isHidden: false,
    },
    // 6. Tên Chú Rể
    {
      id: "layer-txt-groom",
      type: "text",
      name: "Tên Chú Rể",
      text: "Minh Quân",
      fontSize: 30,
      fontFamily: "'Playfair Display', serif",
      fontWeight: "bold",
      fill: "#221A12",
      textAlign: "center",
      x: 0,
      y: 122,
      width: 390,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 6,
      isLocked: false,
      isHidden: false,
    },
    // 7. Dấu Nối Hoàng Kim
    {
      id: "layer-txt-ampersand",
      type: "text",
      name: "Dấu Nối",
      text: "— 💍 —",
      fontSize: 14,
      fontFamily: "Inter, sans-serif",
      fontWeight: "bold",
      fill: "#B78628",
      textAlign: "center",
      x: 0,
      y: 160,
      width: 390,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 7,
      isLocked: false,
      isHidden: false,
    },
    // 8. Tên Cô Dâu
    {
      id: "layer-txt-bride",
      type: "text",
      name: "Tên Cô Dâu",
      text: "Thanh Trúc",
      fontSize: 30,
      fontFamily: "'Playfair Display', serif",
      fontWeight: "bold",
      fill: "#221A12",
      textAlign: "center",
      x: 0,
      y: 184,
      width: 390,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 8,
      isLocked: false,
      isHidden: false,
    },
    // 9. Ảnh Cưới Chính
    {
      id: "layer-img-couple",
      type: "image",
      name: "Ảnh Cưới Bìa",
      src: "https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=600&auto=format&fit=crop",
      x: 65,
      y: 232,
      width: 260,
      height: 310,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 9,
      isLocked: false,
      isHidden: false,
      borderRadius: 20,
      opacity: 1,
    },
    // 10. Lời Mời
    {
      id: "layer-txt-invite",
      type: "text",
      name: "Lời Mời",
      text: "Trân trọng kính mời quý khách tới tham dự",
      fontSize: 13,
      fontFamily: "Inter, sans-serif",
      fontWeight: "normal",
      fontStyle: "italic",
      fill: "#6D5E4D",
      textAlign: "center",
      x: 0,
      y: 565,
      width: 390,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 10,
      isLocked: false,
      isHidden: false,
    },
    // 11. Ngày Cưới
    {
      id: "layer-txt-date",
      type: "text",
      name: "Ngày Cưới",
      text: "CHỦ NHẬT • 20.11.2026 • 18:00",
      fontSize: 13,
      fontFamily: "Inter, sans-serif",
      fontWeight: "bold",
      fill: "#B78628",
      textAlign: "center",
      letterSpacing: 1.5,
      x: 0,
      y: 595,
      width: 390,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 11,
      isLocked: false,
      isHidden: false,
    },

    // ==================== PHẦN 2: LỊCH TRÌNH & ĐỊA ĐIỂM ====================
    // 12. Dải Phân Cách Phần 1 & 2
    {
      id: "layer-div-sec-2",
      type: "shape",
      name: "Phân Cách Phần 2",
      shapeType: "divider",
      x: 95,
      y: 650,
      width: 200,
      height: 1.5,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 12,
      isLocked: false,
      isHidden: false,
      fill: "#C59B4B",
      stroke: "#C59B4B",
      strokeWidth: 1,
    },
    // 13. Tiêu Đề Phần Lịch Trình
    {
      id: "layer-txt-sch-heading",
      type: "text",
      name: "Tiêu Đề Lịch Trình",
      text: "CHƯƠNG TRÌNH HÔN LỄ",
      fontSize: 14,
      fontFamily: "'Playfair Display', serif",
      fontWeight: "bold",
      fill: "#3B2F23",
      textAlign: "center",
      letterSpacing: 2,
      x: 0,
      y: 680,
      width: 390,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 13,
      isLocked: false,
      isHidden: false,
    },
    // 14. Mục 1: Đón Tiếp Khách Mời
    {
      id: "layer-txt-sch-1",
      type: "text",
      name: "Lịch Trình 17:30",
      text: "17:30 • Đón Tiếp Khách Mời & Check-in\nChụp ảnh lưu niệm tại sảnh hoa",
      fontSize: 12,
      fontFamily: "Inter, sans-serif",
      fontWeight: "normal",
      fill: "#4A3E31",
      textAlign: "center",
      lineHeight: 1.4,
      x: 0,
      y: 715,
      width: 390,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 14,
      isLocked: false,
      isHidden: false,
    },
    // 15. Mục 2: Cử Hành Hôn Lễ
    {
      id: "layer-txt-sch-2",
      type: "text",
      name: "Lịch Trình 18:30",
      text: "18:30 • Cử Hành Hôn Lễ Chính Thức\nTrao nhẫn cưới & Cắt bánh mừng",
      fontSize: 12,
      fontFamily: "Inter, sans-serif",
      fontWeight: "normal",
      fill: "#4A3E31",
      textAlign: "center",
      lineHeight: 1.4,
      x: 0,
      y: 770,
      width: 390,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 15,
      isLocked: false,
      isHidden: false,
    },
    // 16. Mục 3: Khai Tiệc
    {
      id: "layer-txt-sch-3",
      type: "text",
      name: "Lịch Trình 19:00",
      text: "19:00 • Khai Tiệc Chiêu Đãi\nThưởng thức ẩm thực & Âm nhạc",
      fontSize: 12,
      fontFamily: "Inter, sans-serif",
      fontWeight: "normal",
      fill: "#4A3E31",
      textAlign: "center",
      lineHeight: 1.4,
      x: 0,
      y: 825,
      width: 390,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 16,
      isLocked: false,
      isHidden: false,
    },
    // 17. Địa Điểm Tổ Chức
    {
      id: "layer-txt-venue-box",
      type: "text",
      name: "Địa Điểm Tiệc Cưới",
      text: "📍 ĐỊA ĐIỂM TỔ CHỨC\nTrung tâm Hội nghị Park Hyatt Sài Gòn\nSố 2 Công Trường Lam Sơn, Quận 1, TP.HCM",
      fontSize: 12,
      fontFamily: "Inter, sans-serif",
      fontWeight: "normal",
      fill: "#221A12",
      textAlign: "center",
      lineHeight: 1.5,
      x: 0,
      y: 890,
      width: 390,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 17,
      isLocked: false,
      isHidden: false,
    },

    // ==================== PHẦN 3: ALBUM ẢNH CƯỚI ====================
    // 18. Dải Phân Cách Phần 2 & 3
    {
      id: "layer-div-sec-3",
      type: "shape",
      name: "Phân Cách Phần 3",
      shapeType: "divider",
      x: 95,
      y: 980,
      width: 200,
      height: 1.5,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 18,
      isLocked: false,
      isHidden: false,
      fill: "#C59B4B",
      stroke: "#C59B4B",
      strokeWidth: 1,
    },
    {
      id: "layer-txt-gal-heading",
      type: "text",
      name: "Tiêu Đề Album",
      text: "KHOẢNH KHẮC HẠNH PHÚC",
      fontSize: 14,
      fontFamily: "'Playfair Display', serif",
      fontWeight: "bold",
      fill: "#3B2F23",
      textAlign: "center",
      letterSpacing: 2,
      x: 0,
      y: 1010,
      width: 390,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 19,
      isLocked: false,
      isHidden: false,
    },
    // 19. Ảnh Cưới 2
    {
      id: "layer-img-gal-1",
      type: "image",
      name: "Ảnh Album 1",
      src: "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?q=80&w=400&auto=format&fit=crop",
      x: 45,
      y: 1045,
      width: 145,
      height: 180,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 20,
      isLocked: false,
      isHidden: false,
      borderRadius: 12,
      opacity: 1,
    },
    // 20. Ảnh Cưới 3
    {
      id: "layer-img-gal-2",
      type: "image",
      name: "Ảnh Album 2",
      src: "https://images.unsplash.com/photo-1583939003579-730e3918a45a?q=80&w=400&auto=format&fit=crop",
      x: 200,
      y: 1045,
      width: 145,
      height: 180,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 21,
      isLocked: false,
      isHidden: false,
      borderRadius: 12,
      opacity: 1,
    },

    // ==================== PHẦN 4: HỘP MỪNG CƯỚI & LỜI CHÚC ====================
    // 21. Dải Phân Cách Phần 3 & 4
    {
      id: "layer-div-sec-4",
      type: "shape",
      name: "Phân Cách Phần 4",
      shapeType: "divider",
      x: 95,
      y: 1260,
      width: 200,
      height: 1.5,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 22,
      isLocked: false,
      isHidden: false,
      fill: "#C59B4B",
      stroke: "#C59B4B",
      strokeWidth: 1,
    },
    {
      id: "layer-txt-gift-heading",
      type: "text",
      name: "Tiêu Đề Mừng Cưới",
      text: "HỘP MỪNG CƯỚI VIETQR",
      fontSize: 14,
      fontFamily: "'Playfair Display', serif",
      fontWeight: "bold",
      fill: "#3B2F23",
      textAlign: "center",
      letterSpacing: 2,
      x: 0,
      y: 1290,
      width: 390,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 23,
      isLocked: false,
      isHidden: false,
    },
    // 22. Ảnh VietQR Chú Rể
    {
      id: "layer-img-qr-groom",
      type: "image",
      name: "Mã QR Chú Rể",
      src: "https://api.vietqr.io/image/970436-1018899999-compact2.jpg?amount=0&accountName=NGUYEN%20MINH%20QUAN",
      x: 50,
      y: 1330,
      width: 135,
      height: 135,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 24,
      isLocked: false,
      isHidden: false,
      borderRadius: 8,
      opacity: 1,
    },
    // 23. Ảnh VietQR Cô Dâu
    {
      id: "layer-img-qr-bride",
      type: "image",
      name: "Mã QR Cô Dâu",
      src: "https://api.vietqr.io/image/970407-19033888888888-compact2.jpg?amount=0&accountName=TRAN%20THANH%20TRUC",
      x: 205,
      y: 1330,
      width: 135,
      height: 135,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 25,
      isLocked: false,
      isHidden: false,
      borderRadius: 8,
      opacity: 1,
    },
    // 24. Chú Thích VietQR
    {
      id: "layer-txt-qr-caption",
      type: "text",
      name: "Ghi Chú QR",
      text: "Mừng Chú Rể (VCB)        Mừng Cô Dâu (TCB)",
      fontSize: 11,
      fontFamily: "Inter, sans-serif",
      fontWeight: "bold",
      fill: "#B78628",
      textAlign: "center",
      x: 0,
      y: 1475,
      width: 390,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 26,
      isLocked: false,
      isHidden: false,
    },
    // 25. Lời Cảm Ơn Cuối Thiệp
    {
      id: "layer-txt-thanks",
      type: "text",
      name: "Lời Cảm Ơn",
      text: "Sự hiện diện của quý khách là niềm vinh hạnh lớn của gia đình chúng tôi!\n— Trân trọng cảm ơn —",
      fontSize: 12,
      fontFamily: "Inter, sans-serif",
      fontWeight: "normal",
      fontStyle: "italic",
      fill: "#6D5E4D",
      textAlign: "center",
      lineHeight: 1.5,
      x: 0,
      y: 1520,
      width: 390,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 27,
      isLocked: false,
      isHidden: false,
    },
    // 26. Họa Tiết Kết Thiệp
    {
      id: "layer-sticker-end",
      type: "sticker",
      name: "Họa Tiết Kết Thiệp",
      stickerType: "emoji",
      content: "⚜️ ✨ ⚜️",
      x: 0,
      y: 1580,
      width: 390,
      fontSize: 18,
      rotation: 0,
      scaleX: 1,
      scaleY: 1,
      zIndex: 28,
      isLocked: false,
      isHidden: false,
    },
  ],
};
