import { IInvitation } from "@/interfaces/invitation.interface";

export const MOCK_PUBLIC_INVITATION: IInvitation = {
  id: "inv-demo-1",
  slug: "minh-quan-thanh-truc",
  title: "Lễ Thành Hôn Minh Quân & Thanh Trúc",
  description: "Trân trọng kính mời quý khách tới tham dự lễ thành hôn và chung vui cùng gia đình chúng tôi",
  eventType: "WEDDING",
  status: "PUBLISHED",
  eventDate: "2026-11-20T18:00:00.000Z",
  eventTime: "18:00",
  coverImage: "https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=1200&auto=format&fit=crop",
  ogImage: "https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=1200&auto=format&fit=crop",
  documentVersion: 1,
  themeConfig: {
    fontIds: ["playfair", "greatVibes", "inter"],
    primaryColor: "#B78628",
    secondaryColor: "#E8C872",
    accentColor: "#8B2435",
    backgroundColor: "#FAF8F5",
    envelopeColor: "#EADCC9",
    waxSealColor: "#A82424",
    bgMusicUrl: "/audio/wedding-bgm.mp3",
    bgMusicTitle: "Until I Found You - Wedding Acoustic",
    autoPlayMusic: true,
    seasonalEffect: "wedding",
  },
  sectionVisibility: {
    cover: true,
    couple: true,
    countdown: true,
    story: true,
    schedule: true,
    gallery: true,
    bankAccounts: true,
    rsvp: true,
    map: true,
  },
  sectionOrder: ["cover", "countdown", "couple", "schedule", "gallery", "bankAccounts", "rsvp", "map"],
  coupleData: {
    groom: {
      fullName: "Nguyễn Minh Quân",
      shortName: "Minh Quân",
      fatherName: "Nguyễn Văn Hùng",
      motherName: "Lê Thị Mai",
      orderInFamily: "Trưởng Nam",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400&auto=format&fit=crop",
      bio: "Anh tìm thấy em là điều tuyệt vời nhất mà cuộc đời này đã trao tặng.",
    },
    bride: {
      fullName: "Trần Thanh Trúc",
      shortName: "Thanh Trúc",
      fatherName: "Trần Quốc Bảo",
      motherName: "Phạm Thu Hương",
      orderInFamily: "Ái Nữ",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=400&auto=format&fit=crop",
      bio: "Hạnh phúc đơn giản là được cùng anh đi qua những năm tháng bình yên.",
    },
    story: "Chúng tôi gặp nhau vào một chiều mùa thu Hà Nội, và sau 5 năm gắn bó cùng nhau vượt qua bao thăng trầm, hôm nay chúng tôi chính thức về chung một nhà.",
  },
  locationData: {
    venueName: "Trung tâm Hội nghị Khách sạn Park Hyatt Sài Gòn",
    address: "Số 2 Công Trường Lam Sơn, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh",
    mapUrl: "https://maps.google.com/?q=Park+Hyatt+Saigon",
  },
  scheduleData: [
    {
      id: "sch-1",
      title: "Đón Tiếp Khách Mời & Check-in",
      time: "17:30",
      description: "Chụp ảnh lưu niệm cùng Cô Dâu & Chú Rể tại sảnh đón khách",
      iconName: "PhotoCamera",
    },
    {
      id: "sch-2",
      title: "Cử Hành Hôn Lễ",
      time: "18:30",
      description: "Lễ trao nhẫn, rót rượu mừng và cắt bánh cưới",
      iconName: "Favorite",
    },
    {
      id: "sch-3",
      title: "Khai Tiệc Chiêu Đãi",
      time: "19:00",
      description: "Thưởng thức dạ tiệc mừng cùng các tiết mục âm nhạc đặc sắc",
      iconName: "Restaurant",
    },
    {
      id: "sch-4",
      title: "Giao Lưu & After Party",
      time: "20:30",
      description: "Minigame bốc thăm may mắn và tiệc âm nhạc",
      iconName: "MusicNote",
    },
  ],
  galleryData: [
    "https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=800&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?q=80&w=800&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1583939003579-730e3918a45a?q=80&w=800&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?q=80&w=800&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?q=80&w=800&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1529636798458-92182e662485?q=80&w=800&auto=format&fit=crop",
  ],
  bankAccountsData: [
    {
      id: "bank-1",
      bankName: "Vietcombank",
      bankCode: "VCB",
      accountNumber: "1018899999",
      accountHolder: "NGUYEN MINH QUAN",
      role: "groom",
      qrUrl: "https://api.vietqr.io/image/970436-1018899999-compact2.jpg?amount=0&accountName=NGUYEN%20MINH%20QUAN",
    },
    {
      id: "bank-2",
      bankName: "Techcombank",
      bankCode: "TCB",
      accountNumber: "19033888888888",
      accountHolder: "TRAN THANH TRUC",
      role: "bride",
      qrUrl: "https://api.vietqr.io/image/970407-19033888888888-compact2.jpg?amount=0&accountName=TRAN%20THANH%20TRUC",
    },
  ],
  rsvpEnabled: true,
  rsvpConfig: {
    deadlineDate: "2026-11-15",
    maxGuestsPerRsvp: 5,
    requirePhone: true,
  },
  publishedAt: "2026-08-30T00:00:00.000Z",
  createdAt: "2026-08-30T00:00:00.000Z",
  updatedAt: "2026-08-30T00:00:00.000Z",
};
